In [1]:
from CommonImports import *
from TopologySelectionAutomation import *

np.set_printoptions(threshold=sys.maxsize)
%matplotlib inline

### Only increasing number of nodes in the network
##### num_nodes = 6, 8, 10 L_k = 48

In [12]:
#import capacities matrix or work with reduced matrix
num_nodes = 6 #!--change this number and re-run cells--! 
capacity = np.load('capacity_array.npy') 
capacities, flt_ids = pruneCapacity(num_nodes, capacity) 

In [13]:
print(capacities.shape)
print(flt_ids)

(23384, 6, 6)
['LN-172' 'LN-179' 'LN-180' 'LN-201' 'LN-207' 'LN-214']


In [14]:
capacity = capacities[5000, :, :]
print(capacity)

[[  0. 390.   0. 195. 987. 390.]
 [390.   0.   0. 987. 588. 987.]
 [  0.   0.   0.   0.   0.   0.]
 [195. 987.   0.   0. 390. 987.]
 [987. 588.   0. 390.   0. 588.]
 [390. 987.   0. 987. 588.   0.]]


Run through time

In [16]:
source = np.where(flt_ids == 'LN-172')
dest = np.where(flt_ids == 'LN-207')
T=2

rho_hist = np.zeros(capacities.shape[0],)
topo_hist = np.zeros((capacities.shape[0], num_nodes, num_nodes-1))
L_k = 48.0

start_time = time.time()
for i in range(0, capacities.shape[0]):
  
    rho, topology_vals = singleCommodityFlow(num_nodes, source, dest, L_k, T, capacities[i, :, :])
    rho_hist[i] = rho
    topo_hist[i] = topology_vals
    
    if i % 1000 == 999: 
        print('iteration = ', i)
        print('elpased time = ', time.time()-start_time)
print('finished')

iteration =  999
elpased time =  6.230870723724365
iteration =  1999
elpased time =  12.780027627944946
iteration =  2999
elpased time =  19.992520570755005
iteration =  3999
elpased time =  27.315507411956787
iteration =  4999
elpased time =  33.51006054878235
iteration =  5999
elpased time =  40.59217286109924
iteration =  6999
elpased time =  46.862659215927124
iteration =  7999
elpased time =  53.06207466125488
iteration =  8999
elpased time =  59.414159059524536
iteration =  9999
elpased time =  65.49494743347168
iteration =  10999
elpased time =  70.95207691192627
iteration =  11999
elpased time =  76.77517676353455
iteration =  12999
elpased time =  82.48530220985413
iteration =  13999
elpased time =  87.85456895828247
iteration =  14999
elpased time =  92.99980306625366
iteration =  15999
elpased time =  97.18642497062683
iteration =  16999
elpased time =  101.59624791145325
iteration =  17999
elpased time =  105.99813747406006
iteration =  18999
elpased time =  110.54512023925

In [17]:
fname = 'Rho vs. Time Nodes = %s.png' % (num_nodes)
fig_title = 'Rho (p) vs. Time for  Source = %s and Destination = %s' %(flt_ids[source-1], flt_ids[dest-1])

times = np.arange(np.datetime64('2021-01-01'),
                  np.datetime64('2021-01-18'), np.timedelta64(1, 'm'))

times = times[1:capacities.shape[0]+1]

fig, ax = plt.subplots()
ax.set_xlabel('Time (days)')
ax.set_ylabel(r"$\rho$")
ax.set_title(fig_title, pad=15)

ax.plot(times, rho_hist, label ='p')
ax.tick_params(axis='x', labelrotation = 45)
plt.savefig(fname, dpi = 300, bbox_inches='tight')

TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

In [19]:
source[0]

array([0])